sudo: false
language: node_js
node_js:
  - 'stable'
  - '<%= nodeTarget %>'
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^v[0-9].*$/
